name: "Deploy app to Shopify Oxygen"
branding:
  icon: shopping-bag
  colour: green
description: "Deploy JavaScript applications to Shopify Oxygen directly from GitHub"
inputs:
  build_command:
    description: The build command to execute; OXYGEN_ASSET_BASE_URL is available as a reference to Shopify's CDN for this command
    required: true
  oxygen_deployment_token:
    description: The JWT deployment token
    required: true
  oxygen_worker_dir:
    description: The name of the directory containing the worker file
    default: dist/worker
  oxygen_client_dir:
    description: The name of the directory with compiled client files
    default: dist/client
  oxygen_deployment_verification:
    description: Verify the worker deployment to Oxygen has been completed (`true` or `false`)
    default: true
  oxygen_deployment_verification_max_duration:
    description: The maximum duration in seconds to wait for the health check to pass
    default: 180
  path:
    description: The root path of the project to deploy
  node_version:
    description: Node version required to build the project
    default: 16
outputs:
  url:
    description: URL of the deployment
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.node_version }}
    - ${{ inputs.build_command }}
    - ${{ inputs.oxygen_deployment_token }}
    - ${{ inputs.path }}
    - ${{ inputs.oxygen_worker_dir }}
    - ${{ inputs.oxygen_client_dir }}
    - ${{ inputs.oxygen_deployment_verification_max_duration }}
    - ${{ inputs.oxygen_deployment_verification }}
